mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0001
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0002
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0003
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0004
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0005
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0006
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0007
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0008
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0009
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0010
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0011
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0012
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0013
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0014
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0015
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0016
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0017
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0018
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0019
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0020
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0021
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0022
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0023
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0024
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0025
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0026
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0027
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0028
mkdir -p /var/lib/origin/openshift.local.volumes/pv/pv0029

chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0001
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0002
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0003
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0004
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0005
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0006
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0007
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0008
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0009
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0010
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0011
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0012
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0013
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0014
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0015
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0016
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0017
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0018
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0019
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0020
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0021
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0022
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0023
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0024
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0025
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0026
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0027
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0028
chmod 777 /var/lib/origin/openshift.local.volumes/pv/pv0029
